title: "Lab04 CPG Streaming"
author: "23120099 Le Xuan Tri, 23120180 Tran Le Trung Truc, 23120166 Tran Huu Kim Thanh, 23120185 Nguyen Ho Anh Tuan"
logo: ""
execute:
  execute_notebooks: "off"
repository:
  url: "https://github.com/emanhthangngot/lab04-datasets-cpg"
  path_to_book: "book"
  branch: "main"
html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
