# Task 4 — Direct Kafka-to-Neo4j ingestion

Evidence run metadata is read from `screenshots/stage2_manifest.json`. Command: `bash scripts/capture_store_evidence.sh`. Kafka Connect uses `org.neo4j.connectors.kafka.sink.Neo4jConnector`; Spark is deliberately absent from this graph route. Raw query output: [`node_count.txt`](../screenshots/neo4j/node_count.txt).


In [1]:
from pathlib import Path
import json
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'screenshots/stage2_manifest.json').exists())
m = json.loads((ROOT / 'screenshots/stage2_manifest.json').read_text())['metrics']['neo4j']
print('total nodes:', m['total_nodes'])
print('explicit CPG nodes:', m['explicit_nodes'])
print('CALL_UNRESOLVED placeholders:', m['placeholders'])
print('relationships:', m['edges'])
print('duplicate node/edge groups:', m['duplicate_node_groups'], '/', m['duplicate_edge_groups'])
assert m == {'total_nodes': 22628, 'explicit_nodes': 21415, 'placeholders': 1213, 'edges': 7968, 'duplicate_node_groups': 0, 'duplicate_edge_groups': 0}


total nodes: 22628
explicit CPG nodes: 21415
CALL_UNRESOLVED placeholders: 1213
relationships: 7968
duplicate node/edge groups: 0 / 0


## Reflection

**Worked:** the connector reached `RUNNING`, upserted 21,415 explicit nodes and 7,968 relationships, and created 1,213 deterministic unresolved-call placeholders. **Failed:** CLI automation cannot manufacture a trustworthy database UI image, and the integrated browser bridge was unavailable in this session. **Resolution:** the chapter cites real Cypher output, duplicate checks, connector status, and a hash-validated manifest; no UI screenshot is claimed.
